version: 1.0.0.{build}
pull_requests:
  do_not_increment_build_number: true
image: Visual Studio 2017
before_build:
- cmd: >-
    msbuild /t:Restore src/Plugin.VoiceToText.sln

    msbuild /t:Clean src/Plugin.VoiceToText.sln

    msbuild src/Plugin.VoiceToText.sln
build:
  project: src/Plugin.VoiceToText.sln
  verbosity: minimal
